AWSTemplateFormatVersion: "2010-09-09"
Description: Sample S3 Bucket
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: factweavers-aws-training-s3-bucket-jojo



# Bucket NAme should be globally unique 